// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csvsplitter.actions;

import java.io.IOException;
import java.io.InputStream;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CountExcelFile extends CustomJavaAction<java.lang.Long>
{
	/** @deprecated use InputFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __InputFile;
	private final system.proxies.FileDocument InputFile;

	public CountExcelFile(
		IContext context,
		IMendixObject _inputFile
	)
	{
		super(context);
		this.__InputFile = _inputFile;
		this.InputFile = _inputFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _inputFile);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (InputFile == null) {
			Core.getLogger("ExcelSplitter").error("Invalid input parameters");
			throw new IllegalArgumentException("Invalid input parameters.");
		}
		long TotalRow = 0;
		try(InputStream inputStream = Core.getFileDocumentContent(getContext(), InputFile.getMendixObject());
				XSSFWorkbook workbook = new XSSFWorkbook(inputStream)) {
			Sheet sheet = workbook.getSheetAt(0);
			int dataRowCount = 0;
			for (Row row : sheet) {
                if (isRowNotEmpty(row)) {
                    dataRowCount++;
                }
            }
			TotalRow = dataRowCount;
		}catch (IOException e) {
			Core.getLogger("ExcelSplitter").error("Error reading Excel file: " + e.getMessage());
			throw new Exception("Error processing Excel file", e);
		}
		return TotalRow;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CountExcelFile";
	}

	// BEGIN EXTRA CODE
	 private static boolean isRowNotEmpty(Row row) {
		for (Cell cell : row) {
			if (cell.getCellType() != CellType.BLANK) {
				 return true;
			}
		}
	        return false;
	}
	// END EXTRA CODE
}
