// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csvsplitter.actions;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import system.proxies.FileDocument;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CsvSplitter extends CustomJavaAction<java.util.List<IMendixObject>>
{
	/** @deprecated use sourceFile.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __sourceFile;
	private final system.proxies.FileDocument sourceFile;
	private final java.lang.Long rowsPerFile;
	private final java.lang.Boolean IncludeHeader;

	public CsvSplitter(
		IContext context,
		IMendixObject _sourceFile,
		java.lang.Long _rowsPerFile,
		java.lang.Boolean _includeHeader
	)
	{
		super(context);
		this.__sourceFile = _sourceFile;
		this.sourceFile = _sourceFile == null ? null : system.proxies.FileDocument.initialize(getContext(), _sourceFile);
		this.rowsPerFile = _rowsPerFile;
		this.IncludeHeader = _includeHeader;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		InputStream inputStream = null;
		BufferedReader reader = null;
		List<IMendixObject> splitFiles = new ArrayList<>();
		int fileIndex = 0;
		int currentRow = 0;
		
		try {
			inputStream = Core.getFileDocumentContent(context(), sourceFile.getMendixObject());
			reader = new BufferedReader(new InputStreamReader(inputStream));
			
			String header = null;
			String row;
			List<String> chunkRows = new ArrayList<>();
			
			// Read header if requested
	        if (IncludeHeader != null && IncludeHeader) {
	            header = reader.readLine();
	        }
			
			while ((row = reader.readLine()) != null) {
				chunkRows.add(row);
				currentRow++;
				
				if (currentRow % rowsPerFile == 0) {
	                fileIndex++;
	                List<String> outputRows = new ArrayList<>();
	                if (IncludeHeader != null && IncludeHeader && header != null) {
	                    outputRows.add(header);
	                }
	                outputRows.addAll(chunkRows);

	                FileDocument chunkFile = createFileDocument(context(), "Chunk_" + fileIndex + ".csv", outputRows);
	                splitFiles.add(chunkFile.getMendixObject());
	                chunkRows.clear();
	            }
			}
			if (!chunkRows.isEmpty()) {
				fileIndex++;
				List<String> outputRows = new ArrayList<>();
	            if (IncludeHeader != null && IncludeHeader && header != null) {
	                outputRows.add(header);
	            }
	            outputRows.addAll(chunkRows);

	            FileDocument chunkFile = createFileDocument(context(), "Chunk_" + fileIndex + ".csv", outputRows);
	            splitFiles.add(chunkFile.getMendixObject());
			}
		}finally {
			ILogNode logger = com.mendix.core.Core.getLogger("CSV-Splitter-JavaAction");
			if (reader != null) {
				try {
					reader.close();
				}catch (Exception e) {
					logger.error("An error occurred: " + e.getMessage(), e);
				}
			}
			if (inputStream != null) {
				try {
		            inputStream.close();
		        } catch (Exception e) {
		        	logger.error("An error occurred: " + e.getMessage(), e);
		        }
			}
		}
		
		return splitFiles;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CsvSplitter";
	}

	// BEGIN EXTRA CODE
	private FileDocument createFileDocument(IContext context, String fileName, List<String> content) throws Exception {
		FileDocument fileDoc = new FileDocument(context);
		fileDoc.setName(context, fileName);
		fileDoc.setName(context, fileName);
		String fileContent = String.join("\n", content);
		InputStream inputStream = new ByteArrayInputStream(fileContent.getBytes());
		Core.storeFileDocumentContent(context, fileDoc.getMendixObject(), inputStream);
		inputStream.close();
		return fileDoc;
	}
	// END EXTRA CODE
}
